apiVersion: apps/v1

replicaCount: 2

env:
  NODE_ENV: production
  MONGO_URI: "mongodb://devops-app-mongodb-service:27017/devopsdb"

deployment:
  name: devops-app
  app: devops-assignment
  replicas: 1
  containerName: devops-app-container
  image:
    repository: devops-assignment
    tag: "1.0"
    pullPolicy: IfNotPresent
  port: 8080
  command: ["node"]
  args: ["k8s-test.js"]
  resources:
    requests:
      memory: "256Mi"
      cpu: "50m"
    limits:
      memory: "1Gi"

service:
  name: devops-app-service
  app: devops-assignment
  type: NodePort
  port: 8080
  nodePort: 32222

mongoDeployment:
  name: mongodb
  app: mongodb
  replicas: 1
  containerName: mongodb
  image:
    repository: mongo
    tag: "6.0"
    pullPolicy: IfNotPresent
  port: 27017

mongoService:
  name: devops-app-mongodb-service
  app: mongodb
  port: 27017
  type: ClusterIP

rollingUpdate:
  maxUnavailable: 0
  maxSurge: 2

features:
  createDeployments: true
  createServices: true
  createHPA: false
  createJob: false
  createScaleUpCronJob: false
  createScaleDownCronJob: false
  createCertificates: false
